### ISSUE TITLE
Credentials not working on iOS 16.5.1

### ISSUE THREAD

**Issue by ManuLpz4** [Cap-go/capacitor-native-biometric#1]
Hey guys! How's it going? Hope you are doing well :)

I'm using ``@capgo/capacitor-native-biometric`` to set and retrieve the user's credentials to then sign in but I updated the iOS version and now it doesn't work anymore. Any suggestion?

Error message:
```
"The operation couldn’t be completed. (CapgoCapacitorNativeBiometric.NativeBiometric.KeychainError error 1.)"
```

**Comment by SergeiPleshkov** [comment]
Hi, i have the same issue. I have dev and prod applications with same backend, and it works fine on dev app, but on prod i receive after successful face recognition. @ManuLpz did you manage to fix it?
```
⚡️  To Native ->  NativeBiometric verifyIdentity 12636790
⚡️  TO JS undefined
⚡️  To Native ->  NativeBiometric getCredentials 12636791
ERROR MESSAGE:  {"errorMessage":"The operation couldn’t be completed. (CapgoCapacitorNativeBiometric.NativeBiometric.KeychainError error 1.)","message":"The operation couldn’t be completed. (CapgoCapacitorNativeBiometric.NativeBiometric.KeychainError error 1.)"}
```
