### ISSUE TITLE
bug: @capgo/capacitor-native-biometric is not compatible with @capacitor/core 6.0.0.

### ISSUE THREAD

**Issue by mantosh59** [Cap-go/capacitor-native-biometric#13]
@capgo/capacitor-native-biometric is not compatible with @capacitor/core 6.0.0.

**Comment by The-Don-Himself** [comment]
I don't think that it's not compatible but rather has a hardset peer dependency on @capacitor/core 5.x.x.
Looking through the changelog, I think it can still work with 6.x.x with minimal changes. I can test locally and attempt a quick PR by evening.

**Comment by cardacci** [comment]
There is a new version uploaded to this repository that I understand adapts this plugin to Capacitor 6, it is here:
https://github.com/Cap-go/capacitor-native-biometric/commit/cfe94d5e5b63fbef5bcb41174502bb4b97eb6c74

I don't see documentation on whether changes need to be made to our particular projects.

**Comment by riderx** [comment]
The plugin has been updated to capacitor 6
