### ISSUE TITLE
Capacitor 6 support

### ISSUE THREAD

**Issue by kientrant1** [Cap-go/capacitor-native-biometric#15]
[Capacitor 6](https://ionic.io/blog/announcing-capacitor-6-0) has been announced and released. Do we have any chance to adapt?

**Comment by cardacci** [comment]
There is a new version uploaded to this repository that I understand adapts this plugin to Capacitor 6, it is here:
https://github.com/Cap-go/capacitor-native-biometric/commit/cfe94d5e5b63fbef5bcb41174502bb4b97eb6c74

I don't see documentation on whether changes need to be made to our particular projects.

**Comment by riderx** [comment]
Version 6 of the plugin supports capacitor 6, nothing change in your side normally

**Comment by kientrant1** [comment]
@riderx I see that version 6 was released. README just mentions about Capacitor 5. I think everyone can have a bit confuse if reading it.

**Comment by riderx** [comment]
Oh yes I totally forgot to update the readme thanks, it’s fixed now
