### ISSUE TITLE
bug: In IOS 17, the plugin propably does not work properly

### ISSUE THREAD

**Issue by meesha81** [Cap-go/capacitor-native-biometric#5]
Hi,
it looks like IOS 17 is not supported by the plugin at this time.  By mistake, I posted to original epicshaggy. Error will probably be related to your fork.

We get an error: 
Error: The operation couldn't be completed. (CapgoCapacitorNativeBiometric.NativeBiometric.KeyChainError error 0

when we call

```
        await NativeBiometric.setCredentials({
          username: credentials.email,
          password: credentials.password,
          server: APP_ID,
        });

```

It would be nice if the plugin supports the new IOS 17 as well.

Thank you for your interest.

**Comment by SergeiPleshkov** [comment]
@meesha81 is it still an issue? we plan to release an app that uses this plugin in a week

**Comment by meesha81** [comment]
This is still issue if you want to use internal storage of faceid. Face id works, but unable to store data in encrypted faceid store. It works up to IOS16. 29. 8. 2023 v 10:08, Sergei Pleshkov ***@***.***>:﻿
@meesha81 is it still an issue? we plan to release an app that uses this plugin in a week

**Comment by riderx** [comment]
Thanks for reporting this, i will place a bounty on it and let someone from the community try to fix it i believe it's not so complex .

**Comment by sagun-gautam** [comment]
I tested my app with this plugin for iOS 17.0.1 & 17.0.2, works fine using all the methods availables:

[isAvailable(...)](https://github.com/Cap-go/capacitor-native-biometric#isavailable)
[verifyIdentity(...)](https://github.com/Cap-go/capacitor-native-biometric#verifyidentity)
[getCredentials(...)](https://github.com/Cap-go/capacitor-native-biometric#getcredentials)
[setCredentials(...)](https://github.com/Cap-go/capacitor-native-biometric#setcredentials)
[deleteCredentials(...)](https://github.com/Cap-go/capacitor-native-biometric#deletecredentials)

**Comment by riderx** [comment]
@meesha81 can you provide more detail ?

**Comment by yagancadorin** [comment]
I got the same issue last week.

Try using the **deleteCredentials** function before calling the **setCredentials** function.

This worked for me.

**Comment by AbidR-S2** [comment]
I'm using the epicShaggy version of this plugin and using deleteCredentials before calling setCredentials worked for me too.
