### ISSUE TITLE
bug: Android (FaceId) Not Detecting Availability Properly (OnePlus One)

### ISSUE THREAD

**Issue by AdlerJS** [Cap-go/capacitor-native-biometric#8]
### Capacitor Version

```
Latest Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/ios: 5.4.1

Installed Dependencies:

  @capacitor/cli: 5.2.3
  @capacitor/core: 5.2.2
  @capacitor/android: 5.2.2
  @capacitor/ios: 5.2.2
```

### Plugin Version

```
 Installed Dependencies:

   @capgo/cli: 3.13.31
   @capgo/capacitor-native-biometric: 5.1.0


✓ Latest Dependencies:


   @capgo/cli: 3.13.31
   @capgo/capacitor-native-biometric: 5.1.0
```

### Platform(s)
Faceid on newer Android platforms

### Current Behavior

Currently this plugin is checking for the availability of faceId via "android.hardware.biometrics.face" but according to the docs: https://developer.android.com/reference/android/hardware/biometrics/package-summary this on longer exists. Seeing as this was a fork of an older package I believe this was deprecated around Android 11-12 range. This is preventing phones with FaceId from returning "Multiple" or "True" when Touch + FaceId is available or just FaceId is available.

### Expected Behavior
If phone has faceId capability it should be detected as available.

### Code Reproduction
Im logging the following Android code out and it's returning false for a OnePlusOne7 with faceId available and enrolled at the OS level.

```
 boolean hasFaceFeature = getContext().getPackageManager().hasSystemFeature(PackageManager.FEATURE_FACE);
 Log.d("BiometricFeatureCheck", "Device has FEATURE_FACE: " + hasFaceFeature);
```

### Other Technical Details
npm --version output: 8.19.2

node --version output: v16.18.1

pod --version output (iOS issues only): N/A

**Comment by AM-Myrick** [comment]
@AdlerJS Is there a fix out there for this issue?

**Comment by riderx** [comment]
@WcaleNieWolny can you check this ? And ifx if needed

**Comment by AM-Myrick** [comment]
@riderx @WcaleNieWolny has there been any movement on this?

**Comment by riderx** [comment]
@AM-Myrick dis you tried i think it’s fixed

**Comment by riderx** [comment]
@AM-Myrick I just pushed an update, who fixes this and removes all deprecated usage on android. v7.1.3

**Comment by AM-Myrick** [comment]
@riderx Thank you so much, have a great day!
